use crate::error::AdeError;
use crate::recipe::StackRecipe;
use std::path::{Path, PathBuf};

/// Context used when rendering an `AGENTS.md` contract from a stack recipe.
#[derive(Debug, Clone)]
pub struct AgentsContractContext {
    pub project_name: String,
    pub root: Option<String>,
    pub runtime: Option<String>,
}

impl AgentsContractContext {
    pub fn new(project_name: impl Into<String>) -> Self {
        Self {
            project_name: project_name.into(),
            root: None,
            runtime: None,
        }
    }

    pub fn with_root(mut self, root: impl Into<String>) -> Self {
        self.root = Some(root.into());
        self
    }

    pub fn with_runtime(mut self, runtime: impl Into<String>) -> Self {
        self.runtime = Some(runtime.into());
        self
    }
}

/// Renders and optionally writes the canonical agent contract.
pub struct AgentsContractGenerator;

impl AgentsContractGenerator {
    pub fn render(recipe: &StackRecipe, ctx: &AgentsContractContext) -> String {
        let runtime = ctx
            .runtime
            .clone()
            .or_else(|| recipe.runtimes.first().cloned())
            .unwrap_or_else(|| "local".into());

        let root_line = ctx
            .root
            .as_ref()
            .map(|r| format!("- **Root:** `{r}`\n"))
            .unwrap_or_default();

        let toolchain_lines = recipe
            .toolchain
            .iter()
            .map(|(k, v)| format!("- **{k}:** {v}"))
            .collect::<Vec<_>>()
            .join("\n");

        let commands = format_commands(recipe);
        let verify = format_verify_ladder(recipe);

        format!(
            r#"# {name} — Agent Contract

Generated by ADE from stack recipe `{recipe_id}` (`{recipe_name}`).

## Authority Order

1. Law/security/human direction
2. CI, tests, schemas
3. This AGENTS.md
4. `.ade/rules/` scoped rules
5. Task/issue acceptance criteria
6. Provider/adapter files
7. Chat memory

## Golden Path

- **Runtime:** {runtime}
{root_line}{toolchain}
- **Commands:**
{commands}

## Phases

The ADE follows AUDIT → PLAN → EXECUTE routing.

- **AUDIT:** Read-only discovery and scoring. No code changes.
- **PLAN:** Phases, gates, ownership. Read-mostly. Drafts in `docs/` or `.ade/` only.
- **EXECUTE:** Apply approved phases only. Never expand scope.

## Security

- NEVER read/quote `.env`, `*.pem`, `*.key`, `*credentials*.json`, or secrets
- NEVER commit two write-capable agents on one checkout
- NEVER merge or deploy without human approval
- NEVER disable security tools to "make AI work"

## Verify Ladder

| Gate | Command |
|------|---------|
{verify}
"#,
            name = ctx.project_name,
            recipe_id = recipe.id,
            recipe_name = recipe.name,
            runtime = runtime,
            root_line = root_line,
            toolchain = if toolchain_lines.is_empty() {
                String::new()
            } else {
                format!("{toolchain_lines}\n")
            },
            commands = commands,
            verify = verify,
        )
    }

    /// Write `AGENTS.md` under `root`. Refuses to overwrite unless `force`.
    pub fn write(
        root: impl AsRef<Path>,
        recipe: &StackRecipe,
        ctx: &AgentsContractContext,
        force: bool,
    ) -> Result<PathBuf, AdeError> {
        let path = root.as_ref().join("AGENTS.md");
        if path.exists() && !force {
            return Err(AdeError::Other(format!(
                "AGENTS.md already exists at {} (pass --force to overwrite)",
                path.display()
            )));
        }
        std::fs::write(&path, Self::render(recipe, ctx))?;
        Ok(path)
    }
}

fn format_commands(recipe: &StackRecipe) -> String {
    let mut lines = Vec::new();
    if let Some(c) = &recipe.commands.build {
        lines.push(format!("  - Build: `{c}`"));
    }
    if let Some(c) = &recipe.commands.lint {
        lines.push(format!("  - Lint: `{c}`"));
    }
    if let Some(c) = &recipe.commands.format {
        lines.push(format!("  - Format: `{c}`"));
    }
    if let Some(c) = &recipe.commands.test {
        lines.push(format!("  - Test: `{c}`"));
    }
    if lines.is_empty() {
        "  - (none defined by recipe)".into()
    } else {
        lines.join("\n")
    }
}

fn format_verify_ladder(recipe: &StackRecipe) -> String {
    let mut rows = vec!["| G0 | project root present |".to_string()];
    if let Some(c) = &recipe.commands.format {
        if let Some(lint) = &recipe.commands.lint {
            rows.push(format!("| G2 | `{c}` + `{lint}` |"));
        } else {
            rows.push(format!("| G2 | `{c}` |"));
        }
    } else if let Some(lint) = &recipe.commands.lint {
        rows.push(format!("| G2 | `{lint}` |"));
    }
    if let Some(c) = &recipe.commands.test {
        rows.push(format!("| G3 | `{c}` |"));
    }
    rows.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::recipe::builtin_recipe;
    use std::fs;

    #[test]
    fn renders_authority_and_verify_sections() {
        let recipe = builtin_recipe("rust-api-turso").expect("recipe");
        let md = AgentsContractGenerator::render(
            &recipe,
            &AgentsContractContext::new("demo-api").with_root(r"C:\Dev\demo"),
        );
        assert!(md.contains("# demo-api — Agent Contract"));
        assert!(md.contains("Authority Order"));
        assert!(md.contains("cargo clippy -- -D warnings"));
        assert!(md.contains(r"C:\Dev\demo"));
        assert!(md.contains("NEVER read/quote `.env`"));
        assert!(md.contains("| G3 |"));
    }

    #[test]
    fn write_refuses_overwrite_without_force() {
        let dir = std::env::temp_dir().join(format!("ade-agents-{}", uuid::Uuid::new_v4()));
        fs::create_dir_all(&dir).unwrap();
        let recipe = builtin_recipe("business-saas").unwrap();
        let ctx = AgentsContractContext::new("saas");
        AgentsContractGenerator::write(&dir, &recipe, &ctx, false).unwrap();
        let err = AgentsContractGenerator::write(&dir, &recipe, &ctx, false).unwrap_err();
        assert!(err.to_string().contains("already exists"));
        AgentsContractGenerator::write(&dir, &recipe, &ctx, true).unwrap();
        let _ = fs::remove_dir_all(&dir);
    }
}
