//! Guided first-win helpers for Ideal ADE activation (I4).

use crate::audit::{AuditMode, AuditRunner};
use crate::error::AdeError;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;

pub const UNDERSTAND_ARTIFACT_REL: &str = ".ade/artifacts/understand-project.md";
pub const GUIDED_WINS_REL: &str = ".ade/artifacts/guided-wins.json";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum GuidedWinId {
    Understand,
    Verify,
    ImproveAde,
}

impl GuidedWinId {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Understand => "understand",
            Self::Verify => "verify",
            Self::ImproveAde => "improve_ade",
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct GuidedWinsState {
    pub understand: bool,
    pub verify: bool,
    pub improve_ade: bool,
    pub understand_artifact: Option<String>,
}

impl GuidedWinsState {
    pub fn mark(&mut self, win: GuidedWinId) {
        match win {
            GuidedWinId::Understand => self.understand = true,
            GuidedWinId::Verify => self.verify = true,
            GuidedWinId::ImproveAde => self.improve_ade = true,
        }
    }

    pub fn completed_count(&self) -> u32 {
        u32::from(self.understand) + u32::from(self.verify) + u32::from(self.improve_ade)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UnderstandResult {
    pub path: String,
    pub summary: String,
    pub wins: GuidedWinsState,
}

/// Write a deterministic understand-project markdown artifact and mark the win.
pub fn write_understand_project(root: impl AsRef<Path>) -> Result<UnderstandResult, AdeError> {
    let root = root.as_ref();
    let markdown = render_understand_markdown(root)?;
    let rel = UNDERSTAND_ARTIFACT_REL;
    let path = root.join(rel);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&path, &markdown)?;

    let mut wins = load_wins(root)?;
    wins.understand = true;
    wins.understand_artifact = Some(rel.replace('\\', "/"));
    save_wins(root, &wins)?;

    Ok(UnderstandResult {
        path: rel.replace('\\', "/"),
        summary: first_paragraph(&markdown),
        wins,
    })
}

pub fn load_wins(root: impl AsRef<Path>) -> Result<GuidedWinsState, AdeError> {
    let path = root.as_ref().join(GUIDED_WINS_REL);
    if !path.is_file() {
        return Ok(GuidedWinsState::default());
    }
    let raw = fs::read_to_string(path)?;
    Ok(serde_json::from_str(&raw)?)
}

pub fn mark_win(root: impl AsRef<Path>, win: GuidedWinId) -> Result<GuidedWinsState, AdeError> {
    let root = root.as_ref();
    let mut wins = load_wins(root)?;
    wins.mark(win);
    save_wins(root, &wins)?;
    Ok(wins)
}

fn save_wins(root: &Path, wins: &GuidedWinsState) -> Result<(), AdeError> {
    let path = root.join(GUIDED_WINS_REL);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let raw = serde_json::to_string_pretty(wins)?;
    fs::write(path, raw)?;
    Ok(())
}

fn render_understand_markdown(root: &Path) -> Result<String, AdeError> {
    let name = root
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("workspace");
    let audit = AuditRunner::new(root).run(AuditMode::EvaluateExisting);
    let stack = detect_stack(root);
    let top = list_top_entries(root);
    let agents = root.join("AGENTS.md").is_file();
    let rules = count_files(&root.join(".ade").join("rules"), "mdc");
    let skills = count_skill_dirs(&root.join(".ade").join("skills"));

    let mut out = String::new();
    out.push_str("# Understand project\n\n");
    out.push_str(&format!("Generated by ADE guided win for `{name}`.\n\n"));
    out.push_str("## Snapshot\n\n");
    out.push_str(&format!("- Root: `{}`\n", root.display()));
    out.push_str(&format!("- Stack signals: {}\n", stack.join(", ")));
    out.push_str(&format!(
        "- Readiness: {}/{} (audit evaluate_existing)\n",
        audit.score, audit.score_max
    ));
    out.push_str(&format!(
        "- AGENTS.md: {}\n",
        if agents { "present" } else { "missing" }
    ));
    out.push_str(&format!("- `.ade/rules`: {rules} files\n"));
    out.push_str(&format!("- `.ade/skills`: {skills} skills\n\n"));

    out.push_str("## Top-level layout\n\n");
    if top.is_empty() {
        out.push_str("- (empty)\n\n");
    } else {
        for entry in top {
            out.push_str(&format!("- `{entry}`\n"));
        }
        out.push('\n');
    }

    out.push_str("## Audit layers\n\n");
    for finding in &audit.findings {
        out.push_str(&format!(
            "- **{}** ({}/{}): {}\n",
            finding.layer, finding.points, finding.points_max, finding.detail
        ));
    }
    out.push('\n');

    if !audit.blockers.is_empty() {
        out.push_str("## Blockers\n\n");
        for blocker in &audit.blockers {
            out.push_str(&format!("- {blocker}\n"));
        }
        out.push('\n');
    }

    out.push_str("## Suggested next wins\n\n");
    out.push_str("1. Run verify through G3 (guided: Run verify)\n");
    out.push_str("2. Improve ADE with a small, verify-gated change (guided: Improve ADE)\n");
    out.push_str("3. Keep Audit under Trust — do not treat the scoreboard as Home\n");

    Ok(out)
}

fn detect_stack(root: &Path) -> Vec<&'static str> {
    let mut signals = Vec::new();
    if root.join("Cargo.toml").is_file() {
        signals.push("rust/cargo");
    }
    if root.join("package.json").is_file() {
        signals.push("node/npm");
    }
    if root.join("pyproject.toml").is_file() || root.join("requirements.txt").is_file() {
        signals.push("python");
    }
    if root.join("apps").join("desktop").is_dir() {
        signals.push("ade-desktop");
    }
    if root.join("crates").is_dir() {
        signals.push("workspace-crates");
    }
    if signals.is_empty() {
        signals.push("unknown");
    }
    signals
}

fn list_top_entries(root: &Path) -> Vec<String> {
    let Ok(entries) = fs::read_dir(root) else {
        return Vec::new();
    };
    let mut names = entries
        .filter_map(Result::ok)
        .map(|entry| {
            let name = entry.file_name().to_string_lossy().into_owned();
            if entry.path().is_dir() {
                format!("{name}/")
            } else {
                name
            }
        })
        .filter(|name| {
            !name.starts_with('.')
                && name != "target/"
                && name != "ade-target/"
                && name != "node_modules/"
        })
        .collect::<Vec<_>>();
    names.sort();
    names.truncate(24);
    names
}

fn count_files(dir: &Path, ext: &str) -> usize {
    let Ok(entries) = fs::read_dir(dir) else {
        return 0;
    };
    entries
        .filter_map(Result::ok)
        .filter(|entry| entry.path().extension().and_then(|value| value.to_str()) == Some(ext))
        .count()
}

fn count_skill_dirs(dir: &Path) -> usize {
    let Ok(entries) = fs::read_dir(dir) else {
        return 0;
    };
    entries
        .filter_map(Result::ok)
        .filter(|entry| entry.path().is_dir() && entry.path().join("SKILL.md").is_file())
        .count()
}

fn first_paragraph(markdown: &str) -> String {
    markdown
        .lines()
        .find(|line| !line.is_empty() && !line.starts_with('#'))
        .unwrap_or("Understand artifact written")
        .trim()
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::env;

    #[test]
    fn writes_understand_artifact_and_marks_win() {
        let root = env::temp_dir().join(format!("ade-guided-{}", uuid::Uuid::new_v4()));
        fs::create_dir_all(root.join("crates")).unwrap();
        fs::write(root.join("Cargo.toml"), "[workspace]\nmembers=[]\n").unwrap();
        fs::write(root.join("AGENTS.md"), "# Agents\n").unwrap();

        let result = write_understand_project(&root).unwrap();
        assert_eq!(result.path, UNDERSTAND_ARTIFACT_REL.replace('\\', "/"));
        assert!(root.join(UNDERSTAND_ARTIFACT_REL).is_file());
        assert!(result.wins.understand);
        let body = fs::read_to_string(root.join(UNDERSTAND_ARTIFACT_REL)).unwrap();
        assert!(body.contains("Understand project"));
        assert!(body.contains("rust/cargo"));

        let wins = mark_win(&root, GuidedWinId::Verify).unwrap();
        assert!(wins.verify);
        assert!(wins.understand);

        let _ = fs::remove_dir_all(root);
    }
}
